const mockResults = [
    {
      id: '1',
      companyName: 'TechNova',
      email: 'contact@technova.com',
      personName: 'Alice Johnson',
      role: 'Software Engineer',
      location: 'San Francisco, CA',
      industry: 'Technology',
    },
    {
      id: '2',
      companyName: 'InnoSoft Solutions',
      email: 'info@innosoft.com',
      personName: 'Bob Smith',
      role: 'Product Manager',
      location: 'Austin, TX',
      industry: 'Software',
    },
    {
      id: '3',
      companyName: 'CloudHive',
      email: 'support@cloudhive.com',
      personName: 'Charlie Adams',
      role: 'Cloud Architect',
      location: 'Seattle, WA',
      industry: 'Cloud Computing',
    },
    {
      id: '4',
      companyName: 'GreenTech Innovations',
      email: 'hello@greentech.com',
      personName: 'Diana Lopez',
      role: 'Environmental Scientist',
      location: 'Denver, CO',
      industry: 'Green Technology',
    },
    {
      id: '5',
      companyName: 'MedTech Labs',
      email: 'support@medtechlabs.com',
      personName: 'Ethan Brown',
      role: 'Research Analyst',
      location: 'Boston, MA',
      industry: 'Healthcare',
    },
    {
      id: '6',
      companyName: 'CyberSecure Inc',
      email: 'contact@cybersecure.com',
      personName: 'Fiona Williams',
      role: 'Security Analyst',
      location: 'New York, NY',
      industry: 'Cybersecurity',
    },
    {
      id: '7',
      companyName: 'EduSphere',
      email: 'info@edusphere.com',
      personName: 'George Taylor',
      role: 'Learning Specialist',
      location: 'Chicago, IL',
      industry: 'Education',
    },
    {
      id: '8',
      companyName: 'FinEdge Partners',
      email: 'support@finedge.com',
      personName: 'Hannah Evans',
      role: 'Financial Advisor',
      location: 'Charlotte, NC',
      industry: 'Finance',
    },
    {
      id: '9',
      companyName: 'AutoDrive Systems',
      email: 'contact@autodrive.com',
      personName: 'Ian Carter',
      role: 'Mechanical Engineer',
      location: 'Detroit, MI',
      industry: 'Automotive',
    },
    {
      id: '10',
      companyName: 'NeoRetail',
      email: 'hello@neoretail.com',
      personName: 'Jessica Clark',
      role: 'Retail Specialist',
      location: 'Los Angeles, CA',
      industry: 'Retail',
    },
  ];
  
export default mockResults;
  